Сикачин Николай. Task 6
EnergyNick/formal-lang-course pull request #4
Opened 2023-03-30 21:15 UTC by EnergyNick

2023-04-01 11:08 UTC, rustam-azimov requested changes

2023-04-01 11:08 UTC, rustam-azimov commented on project/utilities.py
> +    cleared_cfg = cfg.remove_useless_symbols()
Эту строку можно убрать.

2023-04-01 13:27 UTC, EnergyNick commented on project/utilities.py
> +    cleared_cfg = cfg.remove_useless_symbols()
Пофиксил

2023-04-02 08:52 UTC, rustam-azimov approved these changes

2023-04-02 12:38 UTC, merged