Сикачин Николай. Task 7
EnergyNick/formal-lang-course pull request #5
Opened 2023-04-07 20:59 UTC by EnergyNick

2023-04-08 07:56 UTC, rustam-azimov requested changes

2023-04-08 07:56 UTC, rustam-azimov commented on project/ecfg.py
> +        """
Добавьте также чтение из файла

2023-04-08 07:56 UTC, rustam-azimov commented on project/recursive_automath.py
> +class RecursiveAutomaton:
Добавьте функцию для получения матриц смежности из RSM

2023-04-08 11:31 UTC, EnergyNick commented on project/ecfg.py
> +        """
А я получается добавил его в utilities

2023-04-08 12:40 UTC, EnergyNick commented on project/recursive_automath.py
> +class RecursiveAutomaton:
Сделал

2023-04-09 09:36 UTC, rustam-azimov approved these changes

2023-04-09 10:02 UTC, merged